package com.founderz.findemy.domain.academy.entity;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum SiGunGu {
    //서울
    SEOUL("서울, 전체"),
    SEOUL_JUNG_GU("서울, 중구"),
    SEOUL_YONGSAN_GU("서울, 용산구"),
    SEOUL_SEONGDONG_GU("서울, 성동구"),
    SEOUL_GWANGJIN_GU("서울, 광진구"),
    SEOUL_DONGDAEMUN_GU("서울, 동대문구"),
    SEOUL_JUNGNANG_GU("서울, 중랑구"),
    SEOUL_SEONGBUK_GU("서울, 성북구"),
    SEOUL_GANGBUK_GU("서울, 강북구"),
    SEOUL_DOBONG_GU("서울, 도봉구"),
    SEOUL_NOWON_GU("서울, 노원구"),
    SEOUL_EUNPYEONG_GU("서울, 은평구"),
    SEOUL_SEODAEMUN_GU("서울, 서대문구"),
    SEOUL_MAPO_GU("서울, 마포구"),
    SEOUL_YANGCHEON_GU("서울, 양천구"),
    SEOUL_GANGSEO_GU("서울, 강서구"),
    SEOUL_GURO_GU("서울, 구로구"),
    SEOUL_GEUMCHEON_GU("서울, 금천구"),
    SEOUL_YEONGDEUNGPO_GU("서울, 영등포구"),
    SEOUL_DONGJAK_GU("서울, 동작구"),
    SEOUL_GWANAK_GU("서울, 관악구"),
    SEOUL_SEOCHO_GU("서울, 서초구"),
    SEOUL_GANGNAM_GU("서울, 강남구"),
    SEOUL_SONGPA_GU("서울, 송파구"),
    SEOUL_GANGDONG_GU("서울, 강동구"),

    //부산
    BUsAN("부산, 전체"),
    BUSAN_JUNG_GU("부산, 중구"),
    BUSAN_SEO_GU("부산, 서구"),
    BUSAN_DONG_GU("부산, 동구"),
    BUSAN_YEONGDO_GU("부산, 영도구"),
    BUSAN_BUSANJIN_GU("부산, 부산진구"),
    BUSAN_DONGNAE_GU("부산, 동래구"),
    BUSAN_NAM_GU("부산, 남구"),
    BUSAN_BUK_GU("부산, 북구"),
    BUSAN_HAEUNDAE_GU("부산, 해운대구"),
    BUSAN_SAHA_GU("부산, 사하구"),
    BUSAN_GEUMJEONG_GU("부산, 금정구"),
    BUSAN_GANGSEO_GU("부산, 강서구"),
    BUSAN_YEONJE_GU("부산, 연제구"),
    BUSAN_SUYEONG_GU("부산, 수영구"),
    BUSAN_SASANG_GU("부산, 사상구"),
    BUSAN_GIJANG_GUN("부산, 기장군"),

    //대구
    DAEGU("대구, 전체"),
    DAEGU_JUNG_GU("대구, 중구"),
    DAEGU_DONG_GU("대구, 동구"),
    DAEGU_SEO_GU("대구, 서구"),
    DAEGU_NAM_GU("대구, 남구"),
    DAEGU_BUK_GU("대구, 북구"),
    DAEGU_SUSEONG_GU("대구, 수성구"),
    DAEGU_DALSEO_GU("대구, 달서구"),
    DAEGU_DALSEONG_GUN("대구, 달성군"),

    //인천
    INCHEIN("인천, 전체"),
    INCHEON_JUNG_GU("인천, 중구"),
    INCHEON_DONG_GU("인천, 동구"),
    INCHEON_MI_CHU_HOL_GU("인천, 미추홀구"),
    INCHEON_YEONSU_GU("인천, 연수구"),
    INCHEON_NAMDONG_GU("인천, 남동구"),
    INCHEON_BU_PYEONG_GU("인천, 부평구"),
    INCHEON_GYE_YANG_GU("인천, 계양구"),
    INCHEON_SEO_GU("인천, 서구"),
    INCHEON_GANG_HWA_GUN("인천, 강화군"),
    INCHEON_ONG_JIN_GUN("인천, 옹진군"),

    //광주
    GWANGJU("광주, 전체"),
    GWANGJU_DONG_GU("광주, 동구"),
    GWANGJU_SEO_GU("광주, 서구"),
    GWANGJU_NAM_GU("광주, 남구"),
    GWANGJU_BUK_GU("광주, 북구"),
    GWANGJU_GWANGSAN_GU("광주, 광산구"),

    //대전
    DAEJEON("대전, 전체"),
    DAEJEON_DONG_GU("대전, 동구"),
    DAEJEON_JUNG_GU("대전, 중구"),
    DAEJEON_SEO_GU("대전, 서구"),
    DAEJEON_YUSEONG_GU("대전, 유성구"),
    DAEJEON_DAEDEOK_GU("대전, 대덕구"),

    //울산
    ULSAN("울산, 전체"),
    ULSAN_JUNG_GU("울산, 중구"),
    ULSAN_NAM_GU("울산, 남구"),
    ULSAN_DONG_GU("울산, 동구"),
    ULSAN_BUK_GU("울산, 북구"),
    ULSAN_ULJU_GUN("울산, 울주군"),

    //세종
    SEJONG_ALL("세종, 전체"),
    SEJONG("세종, 세종시"),

    //경기도
    GYEONGGI("경기, 전체"),
    GYEONGGI_SUWON_SI("경기도, 수원시"),
    GYEONGGI_SEONGNAM_SI("경기도, 성남시"),
    GYEONGGI_YONGIN_SI("경기도, 용인시"),
    GYEONGGI_ANYANG_SI("경기도, 안양시"),
    GYEONGGI_ANSAN_SI("경기도, 안산시"),
    GYEONGGI_GOYANG_SI("경기도, 고양시"),
    GYEONGGI_BUCHEON_SI("경기도, 부천시"),
    GYEONGGI_UIJEONGBU_SI("경기도, 의정부시"),
    GYEONGGI_ANSEONG_SI("경기도, 안성시"),
    GYEONGGI_NAMYANGJU_SI("경기도, 남양주시"),
    GYEONGGI_HWASEONG_SI("경기도, 화성시"),
    GYEONGGI_PYEONGTAEK_SI("경기도, 평택시"),
    GYEONGGI_UIWANG_SI("경기도, 의왕시"),
    GYEONGGI_GUNPO_SI("경기도, 군포시"),
    GYEONGGI_SIHEUNG_SI("경기도, 시흥시"),
    GYEONGGI_HANAM_SI("경기도, 하남시"),
    GYEONGGI_OSAN_SI("경기도, 오산시"),
    GYEONGGI_ICHEON_SI("경기도, 이천시"),
    GYEONGGI_YEOJU_SI("경기도, 여주시"),
    GYEONGGI_GIMPO_SI("경기도, 김포시"),
    GYEONGGI_PAJU_SI("경기도, 파주시"),
    GYEONGGI_YANGJU_SI("경기도, 양주시"),
    GYEONGGI_DONGDUCHEON_SI("경기도, 동두천시"),
    GYEONGGI_GURI_SI("경기도, 구리시"),
    GYEONGGI_GWANGMYEONG_SI("경기도, 광명시"),
    GYEONGGI_GWANGJU_SI("경기도, 광주시"),
    GYEONGGI_POCHEON_SI("경기도, 포천시"),
    GYEONGGI_YANGPYEONG_GUN("경기도, 양평군"),
    GYEONGGI_GAPYEONG_GUN("경기도, 가평군"),
    GYEONGGI_YEONCHEON_GUN("경기도, 연천군"),

    //충청북도
    CHUNGBUK_CHEONGJU_SI("충청북도, 청주시"),
    CHUNGBUK_CHUNGJU_SI("충청북도, 충주시"),
    CHUNGBUK_JECHEON_SI("충청북도, 제천시"),
    CHUNGBUK_BOEUN_GUN("충청북도, 보은군"),
    CHUNGBUK_OKCHEON_GUN("충청북도, 옥천군"),
    CHUNGBUK_YEONGDONG_GUN("충청북도, 영동군"),
    CHUNGBUK_JINCHEON_GUN("충청북도, 진천군"),
    CHUNGBUK_GOESAN_GUN("충청북도, 괴산군"),
    CHUNGBUK_EUMSEONG_GUN("충청북도, 음성군"),
    CHUNGBUK_DANYANG_GUN("충청북도, 단양군"),
    CHUNGBUK_JEUNGPYEONG_GUN("충청북도, 증평군"),

    //충남
    CHUNGNAM_CHEONAN_SI("충청남도, 천안시"),
    CHUNGNAM_GONGJU_SI("충청남도, 공주시"),
    CHUNGNAM_BORYEONG_SI("충청남도, 보령시"),
    CHUNGNAM_ASAN_SI("충청남도, 아산시"),
    CHUNGNAM_SEOSAN_SI("충청남도, 서산시"),
    CHUNGNAM_NONSAN_SI("충청남도, 논산시"),
    CHUNGNAM_GYERYONG_SI("충청남도, 계룡시"),
    CHUNGNAM_DANGJIN_SI("충청남도, 당진시"),
    CHUNGNAM_GEUMSAN_GUN("충청남도, 금산군"),
    CHUNGNAM_BUYEO_GUN("충청남도, 부여군"),
    CHUNGNAM_SEOCHEON_GUN("충청남도, 서천군"),
    CHUNGNAM_CHEONGYANG_GUN("충청남도, 청양군"),
    CHUNGNAM_HONGSEONG_GUN("충청남도, 홍성군"),
    CHUNGNAM_YESAN_GUN("충청남도, 예산군"),
    CHUNGNAM_TAEAN_GUN("충청남도, 태안군"),

    //전라남도
    JEONNAM_MOKPO_SI("전라남도, 목포시"),
    JEONNAM_YEOSU_SI("전라남도, 여수시"),
    JEONNAM_SUNCHEON_SI("전라남도, 순천시"),
    JEONNAM_NAJU_SI("전라남도, 나주시"),
    JEONNAM_GWANGYANG_SI("전라남도, 광양시"),
    JEONNAM_DAMYANG_GUN("전라남도, 담양군"),
    JEONNAM_GOKSEONG_GUN("전라남도, 곡성군"),
    JEONNAM_GURYE_GUN("전라남도, 구례군"),
    JEONNAM_GOHEUNG_GUN("전라남도, 고흥군"),
    JEONNAM_BOSEONG_GUN("전라남도, 보성군"),
    JEONNAM_HWASUN_GUN("전라남도, 화순군"),
    JEONNAM_JANGHEUNG_GUN("전라남도, 장흥군"),
    JEONNAM_GANGJIN_GUN("전라남도, 강진군"),
    JEONNAM_HAENAM_GUN("전라남도, 해남군"),
    JEONNAM_YEONGAM_GUN("전라남도, 영암군"),
    JEONNAM_MUAN_GUN("전라남도, 무안군"),
    JEONNAM_HAMPYEONG_GUN("전라남도, 함평군"),
    JEONNAM_YEONGKWANG_GUN("전라남도, 영광군"),
    JEONNAM_JANGSEONG_GUN("전라남도, 장성군"),
    JEONNAM_WANDO_GUN("전라남도, 완도군"),
    JEONNAM_JINDO_GUN("전라남도, 진도군"),
    JEONNAM_SINAN_GUN("전라남도, 신안군"),

    //전라북도
    JEONBUK_JEONJU_SI("전라북도, 전주시"),
    JEONBUK_GUNSAN_SI("전라북도, 군산시"),
    JEONBUK_IKSAN_SI("전라북도, 익산시"),
    JEONBUK_JEONGEUP_SI("전라북도, 정읍시"),
    JEONBUK_NAMWON_SI("전라북도, 남원시"),
    JEONBUK_GIMJE_SI("전라북도, 김제시"),
    JEONBUK_WANJU_GUN("전라북도, 완주군"),
    JEONBUK_JINAN_GUN("전라북도, 진안군"),
    JEONBUK_MUJU_GUN("전라북도, 무주군"),
    JEONBUK_JANGSU_GUN("전라북도, 장수군"),
    JEONBUK_IMSIL_GUN("전라북도, 임실군"),
    JEONBUK_SUNCHANG_GUN("전라북도, 순창군"),
    JEONBUK_GOCHANG_GUN("전라북도, 고창군"),
    JEONBUK_BUAN_GUN("전라북도, 부안군"),

    //경상남도
    GYEONGNAM_CHANGWON_SI("경상남도, 창원시"),
    GYEONGNAM_JINJU_SI("경상남도, 진주시"),
    GYEONGNAM_TONGYEONG_SI("경상남도, 통영시"),
    GYEONGNAM_SACHEON_SI("경상남도, 사천시"),
    GYEONGNAM_GIMHAE_SI("경상남도, 김해시"),
    GYEONGNAM_MIRYANG_SI("경상남도, 밀양시"),
    GYEONGNAM_GEOJE_SI("경상남도, 거제시"),
    GYEONGNAM_YANGSAN_SI("경상남도, 양산시"),
    GYEONGNAM_UIRYEONG_GUN("경상남도, 의령군"),
    GYEONGNAM_HAMAN_GUN("경상남도, 함안군"),
    GYEONGNAM_CHANGNYEONG_GUN("경상남도, 창녕군"),
    GYEONGNAM_GOSEONG_GUN("경상남도, 고성군"),
    GYEONGNAM_NAMHAE_GUN("경상남도, 남해군"),
    GYEONGNAM_HADONG_GUN("경상남도, 하동군"),
    GYEONGNAM_SANCHEONG_GUN("경상남도, 산청군"),
    GYEONGNAM_HAMYANG_GUN("경상남도, 함양군"),
    GYEONGNAM_GEOCHANG_GUN("경상남도, 거창군"),
    GYEONGNAM_HAPCHEON_GUN("경상남도, 합천군"),

    //경상북도
    GYEONGBUK_POHANG_SI("경상북도, 포항시"),
    GYEONGBUK_GYEONGJU_SI("경상북도, 경주시"),
    GYEONGBUK_GIMCHEON_SI("경상북도, 김천시"),
    GYEONGBUK_ANDONG_SI("경상북도, 안동시"),
    GYEONGBUK_GUMI_SI("경상북도, 구미시"),
    GYEONGBUK_YEONGJU_SI("경상북도, 영주시"),
    GYEONGBUK_YEONGCHEON_SI("경상북도, 영천시"),
    GYEONGBUK_SANGJU_SI("경상북도, 상주시"),
    GYEONGBUK_MUNGYEONG_SI("경상북도, 문경시"),
    GYEONGBUK_GYEONGSAN_SI("경상북도, 경산시"),
    GYEONGBUK_GUNWI_GUN("경상북도, 군위군"),
    GYEONGBUK_UISEONG_GUN("경상북도, 의성군"),
    GYEONGBUK_CHEONGSONG_GUN("경상북도, 청송군"),
    GYEONGBUK_YEONGYANG_GUN("경상북도, 영양군"),
    GYEONGBUK_YEONGDEOK_GUN("경상북도, 영덕군"),
    GYEONGBUK_CHEONGDO_GUN("경상북도, 청도군"),
    GYEONGBUK_GORYEONG_GUN("경상북도, 고령군"),
    GYEONGBUK_SEONGJU_GUN("경상북도, 성주군"),
    GYEONGBUK_CHILGOK_GUN("경상북도, 칠곡군"),
    GYEONGBUK_YECHEON_GUN("경상북도, 예천군"),
    GYEONGBUK_BONGHWA_GUN("경상북도, 봉화군"),
    GYEONGBUK_ULJIN_GUN("경상북도, 울진군"),
    GYEONGBUK_ULLEUNG_GUN("경상북도, 울릉군"),


    //강원도
    GANGWON_CHUNCHEON_SI("강원도, 춘천시"),
    GANGWON_WONJU_SI("강원도, 원주시"),
    GANGWON_GANGNEUNG_SI("강원도, 강릉시"),
    GANGWON_DONGHAE_SI("강원도, 동해시"),
    GANGWON_TAEBAEK_SI("강원도, 태백시"),
    GANGWON_SOKCHO_SI("강원도, 속초시"),
    GANGWON_SAMCHEOK_SI("강원도, 삼척시"),
    GANGWON_HONGCHEON_GUN("강원도, 홍천군"),
    GANGWON_HOENGSEONG_GUN("강원도, 횡성군"),
    GANGWON_YEONGWOL_GUN("강원도, 영월군"),
    GANGWON_PYEONGCHANG_GUN("강원도, 평창군"),
    GANGWON_JEONGSEON_GUN("강원도, 정선군"),
    GANGWON_CHEORWON_GUN("강원도, 철원군"),
    GANGWON_HWACHEON_GUN("강원도, 화천군"),
    GANGWON_YANGGU_GUN("강원도, 양구군"),
    GANGWON_INJE_GUN("강원도, 인제군"),
    GANGWON_GOSEONG_GUN("강원도, 고성군"),
    GANGWON_YANGYANG_GUN("강원도, 양양군"),

    //제주특별자치도
    JEJU_JEJU_SI("제주특별자치도, 제주시"),
    JEJU_SEOGWIPO_SI("제주특별자치도, 서귀포시");
    private final String name;
}
